export enum PROTOCOL_NAME {
  UNISWAP = 'UniSwap',
  BAKERY_SWAP = 'BakerySwap',
  AIR_NFT = 'AirNFT',
  APE_SWAP = 'ApeSwap',
  AUTO_FARM = 'AutoFarm',
  BEEFY = 'Beefy',
  BELT_FI = 'BeltFi',
  BI_SWAP = 'BiSwap',
  MDEX = 'Mdex',
  PANCAKE_SWAP = 'PancakeSwap',
  SUSHI_SWAP = 'SushiSwap',
  VENUS = 'Venus',
  WAULT_SWAP = 'WaultSwap',
  KLAY_SWAP = 'KlaySwap',
  QUICK_SWAP = 'QuickSwap',
  AAVE = 'Aave',
  TERRA_SWAP = 'TerraSwap',
}
